name: Makefile CI

on:
  push:
    branches: [ "ino_dev" ]
  pull_request:
    branches: [ "ino_dev" ]
  workflow_dispatch:
    inputs:
      tags:
        description: "opis"
  

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:41

    steps:
      - name: Install dependencies
        run: |
          dnf install -y git cmake gcc gcc-c++ make ruby ruby-devel rpm-build rubygems
          gem install --no-document fpm

      - name: Checkout cJSON
        run: |
          git clone https://github.com/DaveGamble/cJSON.git /app

      - name: Build cJSON
        working-directory: /app
        run: |
          mkdir build && cd build
          cmake ..
          make
          make DESTDIR=/tmp/install install

      - name: Create RPM with fpm
        working-directory: /app
        run: |
          fpm -s dir -t rpm \
            -n mycjson \
            -v 1.7.15 \
            -C /tmp/install \
            -p /app/mycjson.rpm

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: mycjson-rpm
          path: /app/mycjson.rpm
